id: P010786
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11807
  title: ཤེར་ཕྱིན་འབུམ་ཊཱིཀ
  author: ''
  volumes:
    9ae1bf8711874fa28cee1824a659a0da:
      image_group_id: I1KG11814
      title: ''
      volume_number: 1
      total_pages: 850
