id: IC3FA93AC
legacy_id: P010786
ocr_import_info:
  bdrc_scan_id: W1KG11807
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T23:09:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:06:40.696240+00:00'
last_modified: 2022-08-31 11:07:21.133989
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11807
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11807
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་འབུམ་ཊཱིཀ
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics:
  ocr_word_mean_confidence_index: 0.742200013442492
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG11814:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11814
      total_pages: 850
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11814.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.742200013442492
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
