id: IC3FA93AC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:15:16+00:00'
last_modified: '2022-06-08T17:31:04.050354+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11807
  title: ཤེར་ཕྱིན་འབུམ་ཊཱིཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6901':
      image_group_id: I1KG11814
      title: ''
      total_pages: 850
      order: 1
      base_file: 6901.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
